### ISSUE TITLE
Make default confirmation selection to yes for ctrl-c

### ISSUE THREAD

**Issue by nokernel** [leg100/pug#51]
**Is your feature request related to a problem? Please describe.**
When I hit ctrl-c my goal is to exit, having the confirmation prompt default to N is counter intuitive for me, I always asume it being Y like alot of linux tools and I simply hit enter but No is selected by default.

**Describe the solution you'd like**
Default to Y for ctrl-c confirmation prompt, as having the prompt is fine enough.
Could also be set as configuration flag for user that do not like the default setting.

**Comment by leg100** [comment]
Can you name some of those linux tools?

One thing to consider here is that there may running tasks when exiting. Currently, when pug exits, it sends a termination signal to any running tasks.

It might be a better UX, to say to the user, "Quitting will terminate N tasks - are you sure?". Whether to default to N or Y....N seems more sensible because this is a disruptive operation.

And of course, even if there are no tasks running, if a user exits pug then lose all their history, which is perhaps not what they want to do (?).

Another option might be that hitting Ctrl-C and then hitting Ctrl-C again quits the program.

**Comment by nokernel** [comment]
Closing this one, to keep list of issue smaller.
